# Importing Numpy Library 

NumPy is a fundamental package for numerical computations in Python, especially for working with arrays and matrices.

In [1]:
import numpy as np

# Creating 1D Array
 This creates a one-dimensional array from a Python list.

In [2]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
# for checking dimensions
arr_1d.ndim

1

In [4]:
#checking the type
type(arr_1d)

numpy.ndarray

In [5]:
arr_1d.dtype

dtype('int32')

# Creating 2D Array
 A 2D array can be created using nested lists like np.array([[1, 2], [3, 4]]), which represents a matrix.

In [6]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
arr_2d.size

8

In [8]:
arr_2d.dtype

dtype('int32')

In [9]:
arr_2d.ndim

2

In [10]:
arr_2d.shape

(2, 4)

# 1's Matrix 
 You can create a matrix filled with ones using np.ones((rows, cols)), where rows and cols specify the dimensions of the matrix.

In [11]:
mx_1s = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(mx_1s)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [12]:
mx_1s.dtype

dtype('int32')

In [13]:
mx_1s.shape

(3, 3)

In [14]:
mx_1s = np.ones((3,4),dtype=int)
mx_1s

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
mx_1s.dtype

dtype('int32')

In [16]:
mx_1s.size

12

# Creating Zero's Matrix
Similarly, a matrix filled with zeros can be created with np.zeros((rows, cols)).

In [17]:
mx_0s = np.zeros((4,6))
mx_0s

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
mx_0s = np.zeros((4,6),dtype = int)
mx_0s

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [19]:
mx_0s = np.zeros((4,6),dtype = bool)
mx_0s

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [20]:
mx_0s = np.zeros((4,6),dtype = str)
mx_0s

array([['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', ''],
       ['', '', '', '', '', '']], dtype='<U1')

# Creating Empty Matrix
An empty matrix (with uninitialized values) can be created using np.empty((rows, cols))

In [21]:
em_mx = np.empty((3,3))
print(em_mx)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 7.115e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


# Numpy Functions
NumPy provides a wide range of functions for array manipulation, mathematical operations, and linear algebra.

# 1- arange()
np.arange(start, stop, step) generates a sequence of numbers from start to stop (exclusive) with a specified step size.



In [22]:
arr_1d = np.arange(1,13)
arr_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
# printing even/odd numbers
arr_1d =np.arange(1,13,2)
print(arr_1d)
arr_1odd=np.arange(1,13,3)
print(arr_1odd)

[ 1  3  5  7  9 11]
[ 1  4  7 10]


# 2-Linspace 
np.linspace(start, stop, num) creates an array of num evenly spaced values between start and stop.

In [24]:
a=np.linspace(1,2,10)
a


array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

# 3-reshape()
np.reshape(array, new_shape) reshapes an array into a new shape specified by new_shape.

In [25]:
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
arr_2d = arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# Change 1d into 2d
You can change the shape of a 1D array to a 2D array using np.reshape(array, (rows, cols)) or array.reshape((rows, cols)).

In [27]:
arr = np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# These are methods for manipulating array shapes (ravel and flatten) or transposing matrices (transpose or T).

# 4-ravel()

In [28]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 5-flatten()

In [29]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 6-transpose()

In [30]:
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# Mathematical Operation Using Numpy
NumPy enables efficient element-wise mathematical operations on arrays, like addition, multiplication, etc.

In [31]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# For Addition

In [32]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [33]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [35]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [38]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [39]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [40]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [41]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

# For Checking Maximum Values of Matrix
Use np.max(array) or array.max() to find the maximum value in an array.

In [42]:
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
arr1.max()

9

In [44]:
#for finding index of that array
arr1.argmax()

8

In [45]:
#column maximum value 
arr1.max(axis = 0)

array([7, 8, 9])

In [46]:
#row maximum value
arr1.max(axis = 1)

array([3, 6, 9])

# For Checking Minimum Values in Matrix
Use np.min(array) or array.min() to find the minimum value in an array.

In [47]:
arr1.min()

1

In [48]:
#for index finding 
arr1.argmax()

8

In [49]:
arr1.min(axis = 0)

array([1, 2, 3])

In [50]:
arr1.min(axis = 1)

array([1, 4, 7])

In [51]:
#for minimum value of column
arr.min(axis = 0)

array([1, 2, 3, 4, 5, 6])

In [52]:
#for minimum value of row
arr1.min(axis = 1)

array([1, 4, 7])

In [53]:
np.sum(arr1)

45

In [54]:
#for column sum
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [55]:
#for row sum
np.sum(arr1, axis = 0)

array([12, 15, 18])

In [56]:
#for average of elements
np.mean(arr1)

5.0

In [57]:
#for square of matrix
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [58]:
#for standard division 
np.std(arr1)

2.581988897471611

In [59]:
#for exponent of element
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [60]:
#for log (natural log) of element
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [61]:
#for log10(base10) of element 
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# Array Slicing
NumPy arrays support slicing to access subsets of data efficiently.

In [62]:
a = np.arange(1,101).reshape(10,10)
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [63]:
a[0,0]

1

In [64]:
#checking the dimensions of array 
a[0,0].ndim
#0 means scalar value

0

In [65]:
#for single row and all column
a[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
#for single column and all rows
a[:, 0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [67]:
a[:,0:1].ndim

2

In [68]:
#for specific row and column
a[1:4, 1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [69]:
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [70]:
#for all rows & 2,3 column
a[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

# Full Matrix

In [71]:
a[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [72]:
a[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [73]:
a[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [74]:
#for item storage space 
a.itemsize

4

In [75]:
a.dtype

dtype('int32')

In [76]:
32/8

4.0

# Array Conctination & Split
NumPy provides functions like np.concatenate() and np.split() to combine or separate arrays along specified axes.

In [77]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [78]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [79]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [80]:
#row concatenation
np.concatenate((arr1,arr2),axis = 1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [81]:
#vertical concatenation
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [82]:
#horizontal concatenation
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

# Split Function
 NumPy's np.split() divides an array into sub-arrays along a specified axis.

In [83]:
np.split(arr1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [84]:
list1 = np.split(arr1,2)
type(list1)

list

In [85]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [86]:
type(list1[0])

numpy.ndarray

In [87]:
#row wise concatenation
np.split(arr1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [88]:
#creating 1d array
d1 = np.array([4,6,7,8,6,5])
np.split(d1,[1,3])

[array([4]), array([6, 7]), array([8, 6, 5])]

# Trignometery Functions
NumPy includes trigonometric functions like np.sin(), np.cos(), np.tan(), etc., which operate element-wise on arrays.

In [89]:
np.sin(180)

-0.8011526357338304

In [90]:
np.sin(90)

0.8939966636005579

In [91]:
np.cos(180)

-0.5984600690578581

In [92]:
np.tan(180)

1.3386902103511544

# Random Sampling With NumPy
NumPy has functions to generate random numbers and samples from various distributions.

In [93]:
import random

In [94]:
np.random.random(1)

array([0.05018561])

In [95]:
np.random.random((3,3))

array([[0.70257458, 0.60626036, 0.45110688],
       [0.28747333, 0.57940126, 0.9029497 ],
       [0.7410242 , 0.22920277, 0.99580384]])

In [96]:
#random.random function is used when we required values from 0 to 1

In [97]:
#for integer type values
np.random.randint(1,4)

3

In [98]:
np.random.randint(1,4,(4,4))

array([[3, 3, 3, 1],
       [1, 2, 2, 3],
       [3, 2, 3, 3],
       [3, 1, 2, 2]])

In [99]:
np.random.randint(1,4,(2,4,4))

array([[[2, 1, 1, 1],
        [3, 1, 1, 3],
        [3, 2, 1, 2],
        [3, 1, 3, 2]],

       [[3, 1, 3, 3],
        [1, 1, 3, 3],
        [3, 3, 1, 3],
        [2, 1, 3, 1]]])

In [100]:
#for same values using random we use seed function
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [101]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [102]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [103]:
x = [1,2,3,4]
np.random.choice(x)

4

In [104]:
for i in range(20):
    print(np.random.choice(x))

1
3
1
2
4
3
1
3
4
1
4
2
3
4
4
1
2
1
3
1


In [105]:
#permutation function
np.random.permutation(x)

array([3, 2, 4, 1])

# String Operations, Comparsion and information
NumPy provides functions to work with string arrays, perform comparison operations, and retrieve information about arrays.

In [106]:
#generate two strings
a = "Hello One"
str1 = "Hello two"
np.char.add(a,str1)

array('Hello OneHello two', dtype='<U18')

In [107]:
#conversion of string in lower case
np.char.lower(a)

array('hello one', dtype='<U9')

In [108]:
#for upper case
np.char.upper(str1)

array('HELLO TWO', dtype='<U9')

In [109]:
#center method
np.char.center(str1,60)

array('                         Hello two                          ',
      dtype='<U60')

In [110]:
np.char.center(str1, 60, fillchar="*")

array('*************************Hello two**************************',
      dtype='<U60')

# Split Function
This is likely related to splitting string arrays into substrings using NumPy's np.char.split().

In [111]:
np.char.split(a)

array(list(['Hello', 'One']), dtype=object)

In [112]:
np.char.splitlines("Hello\npk")

array(list(['Hello', 'pk']), dtype=object)

In [113]:
str4 ="dmy"
str5 = "dmy"
#join method
np.char.join([":","/"],[str4,str5])

array(['d:m:y', 'd/m/y'], dtype='<U5')

In [114]:
#compersion of string
np.char.equal(str4,str5)

array(True)

In [115]:
#count method 
np.char.count(a,"a")

array(0)

In [116]:
np.char.count(a,"l")

array(2)

In [117]:
#particular string is present or not
np.char.find(a,"Ai")

array(-1)

In [118]:
np.char.find(a,"o")

array(4)

In [119]:
np.char.find(a,"Ai")

array(-1)